import { StyleSheet } from 'react-native';

export const catalogUi = {
  cardPurple: '#7C72E4',
  cardCyan: '#35B8D4',
  roomButton: '#F58C83',
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#DDE4EE',
  },
  pageFrame: {
    width: '100%',
    backgroundColor: 'transparent',
  },
  pageContent: {
    flex: 1,
    width: '100%',
  },
  headerSection: {
    width: '100%',
    paddingHorizontal: 28,
    paddingTop: 24,
  },
  cardsScroll: {
    flex: 1,
    width: '100%',
  },
  backgroundMilkOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  cardsContent: {
    width: '100%',
    paddingHorizontal: 28,
    paddingBottom: 24,
    paddingTop: 18,
  },
  sectionIntro: {
    gap: 4,
    marginBottom: 18,
  },
  sectionEyebrow: {
    color: '#8A91AA',
    fontFamily: 'Nunito_800ExtraBold',
    fontSize: 11,
    lineHeight: 14,
    letterSpacing: 1.4,
  },
  sectionTitle: {
    color: '#23254D',
    fontFamily: 'Baloo2_700Bold',
    fontSize: 24,
    lineHeight: 26,
  },
  profileCardShell: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: '#DCE2EC',
    backgroundColor: 'rgba(246,248,252,0.92)',
    paddingHorizontal: 18,
    paddingVertical: 15,
    shadowColor: '#000000',
    shadowOpacity: 0.1,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  profileIdentityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  profileAvatarWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,0.5)',
    borderWidth: 1,
    borderColor: 'rgba(215,223,235,0.78)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileNameText: {
    marginTop: 1,
    fontSize: 20,
    lineHeight: 22,
    color: '#23254D',
    fontFamily: 'Baloo2_700Bold',
    flexShrink: 1,
  },
  catalogTitle: {
    fontFamily: 'Baloo2_700Bold',
    fontStyle: 'italic',
    fontSize: 48,
    lineHeight: 48,
    letterSpacing: 0.8,
    color: '#23254D',
  },
  gameGrid: {
    width: '100%',
    gap: 16,
  },
  gameGridRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    width: '100%',
  },
  gameGridRowSingle: {
    justifyContent: 'flex-start',
  },
  gameGridCell: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 0,
  },
  gameGridCellGap: {
    marginRight: 12,
  },
  gameTilePressable: {
    width: '100%',
    minWidth: 0,
    height: 280,
  },
  gameTileSimple: {
    width: '100%',
    height: '100%',
    borderRadius: 30,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.4)',
    justifyContent: 'space-between',
    overflow: 'hidden',
    paddingTop: 16,
    paddingHorizontal: 16,
    paddingBottom: 18,
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  gameTileGlow: {
    ...StyleSheet.absoluteFillObject,
  },
  gameTileCoverFrame: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'hidden',
    borderRadius: 30,
  },
  gameTileCoverImage: {
    width: '100%',
    height: '100%',
  },
  gameTileImageOverlay: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 30,
    backgroundColor: 'rgba(20,24,52,0.14)',
  },
  cardPurple: {
    backgroundColor: catalogUi.cardPurple,
  },
  cardCyan: {
    backgroundColor: catalogUi.cardCyan,
  },
  gameTileTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  gameModeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    flexShrink: 1,
    borderRadius: 999,
    backgroundColor: 'rgba(248,250,255,0.78)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.82)',
    paddingHorizontal: 8,
    paddingVertical: 6,
    minHeight: 28,
  },
  gameTileBody: {
    flex: 1,
  },
  gameTileSimpleLabel: {
    color: '#FFFFFF',
    fontFamily: 'Baloo2_700Bold',
    fontSize: 22,
    lineHeight: 24,
    letterSpacing: 0.6,
  },
  gameTileFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 6,
    marginTop: 16,
  },
  gamePlayersBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    flexShrink: 1,
    borderRadius: 999,
    backgroundColor: 'rgba(248,250,255,0.78)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.82)',
    paddingHorizontal: 8,
    paddingVertical: 6,
    minHeight: 28,
  },
  gamePlayersBadgeText: {
    color: '#2B2A46',
    fontFamily: 'Nunito_800ExtraBold',
    fontSize: 9,
    lineHeight: 11,
    letterSpacing: 0.6,
  },
  codeButtonDock: {
    width: '100%',
    paddingHorizontal: 28,
    paddingTop: 18,
    alignItems: 'center',
  },
  codeButtonAtom: {
    width: '100%',
    alignSelf: 'center',
    minHeight: 56,
    borderRadius: 20,
    borderWidth: 1.2,
    borderColor: '#DE756D',
    borderBottomWidth: 3,
    borderBottomColor: '#CC665E',
    shadowColor: '#000000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  codeModal: {
    borderRadius: 24,
  },
  avatarModal: {
    borderRadius: 24,
  },
  codeModalTitle: {
    color: '#23254D',
    fontFamily: 'Baloo2_700Bold',
    fontSize: 28,
    lineHeight: 30,
    letterSpacing: 0.4,
  },
  codeModalSubtitle: {
    color: '#4A4A6F',
    fontFamily: 'Nunito_700Bold',
    fontSize: 14,
    lineHeight: 18,
  },
  avatarModalSubtitle: {
    color: '#4A4A6F',
    fontFamily: 'Nunito_700Bold',
    fontSize: 14,
    lineHeight: 18,
  },
  avatarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    paddingTop: 6,
  },
  avatarOption: {
    width: '22%',
    minWidth: 64,
    aspectRatio: 1,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#D7DFEB',
    backgroundColor: '#F6F8FC',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  avatarOptionSelected: {
    borderColor: '#F47D74',
    backgroundColor: '#FFF1EF',
  },
  avatarOptionInner: {
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: 'center',
    justifyContent: 'center',
  },
  codeModalInputWrap: {
    marginTop: 2,
  },
  codeModalInput: {
    minHeight: 52,
    borderRadius: 16,
    borderWidth: 1,
    backgroundColor: 'rgba(255,255,255,0.9)',
    paddingHorizontal: 14,
    textAlign: 'center',
    color: '#23254D',
    fontSize: 22,
    letterSpacing: 1.5,
    lineHeight: 24,
    borderColor: 'rgba(61,57,100,0.35)',
    fontFamily: 'Nunito_800ExtraBold',
  },
  codeModalInputError: {
    borderColor: '#D6456B',
  },
  codeModalError: {
    marginTop: -2,
    color: '#C73961',
    fontFamily: 'Nunito_700Bold',
    fontSize: 12,
    lineHeight: 16,
  },
  codeModalConfirmButton: {
    minHeight: 56,
    borderRadius: 20,
    borderWidth: 1.2,
    borderColor: '#DE756D',
    borderBottomWidth: 3,
    borderBottomColor: '#CC665E',
    shadowColor: '#000000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
    marginTop: 4,
  },
  modeButtonDisabled: {
    opacity: 0.5,
  },
});
