import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  emptyWrap: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  lobbyMilkOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.56)',
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 176,
    gap: 12,
    width: '100%',
    maxWidth: 620,
    alignSelf: 'center',
  },
  sessionPanel: {
    borderWidth: 1.5,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 10,
    shadowOpacity: 0.22,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 7,
  },
  sessionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  sessionTitle: {
    fontSize: 52,
    lineHeight: 54,
  },
  roomCodeWrap: {
    alignItems: 'center',
    gap: 8,
  },
  roomCodeActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  roomCodePill: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    shadowColor: '#93BFEA',
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  roomCodeMaskButton: {
    width: 40,
    height: 40,
    borderRadius: 999,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#93BFEA',
    shadowOpacity: 0.16,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  roomCodeText: {
    fontSize: 24,
    letterSpacing: 2.2,
  },
  subtitle: {
    fontSize: 12,
    textAlign: 'center',
  },
  headerBadges: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 8,
  },
  countdownPill: {
    alignSelf: 'center',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FFFFFF',
  },
  countdownLabel: {
    fontSize: 12,
  },
  countdownValue: {
    fontSize: 18,
    lineHeight: 18,
  },
  realtimeHint: {
    fontSize: 12,
    textAlign: 'center',
  },
  settingsIconButton: {
    width: 42,
    height: 42,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#8CA6DB',
    shadowOpacity: 0.24,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  settingsBlock: {
    gap: 8,
  },
  settingsLabel: {
    fontSize: 13,
  },
  settingsHint: {
    fontSize: 12,
  },
  settingsToggleRow: {
    flexDirection: 'row',
    gap: 8,
  },
  settingsToggle: {
    minHeight: 34,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  settingsToggleText: {
    fontSize: 13,
  },
  settingsStepperRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  stepperControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  stepperButton: {
    width: 30,
    height: 30,
    borderWidth: 1,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperButtonText: {
    fontSize: 19,
    lineHeight: 19,
  },
  stepperValue: {
    minWidth: 24,
    textAlign: 'center',
    fontSize: 15,
  },
  playersList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    alignContent: 'flex-start',
    rowGap: 12,
    columnGap: 10,
  },
  emptyPlayersState: {
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  emptyPlayersText: {
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  playerCell: {
    minWidth: 0,
  },
  playerCard: {
    borderWidth: 1.8,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.92)',
    minHeight: 128,
    shadowOpacity: 0.28,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
    overflow: 'hidden',
  },
  playerCardPressable: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 6,
    minHeight: 126,
  },
  avatarShell: {
    position: 'relative',
    width: 54,
    height: 54,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarOrb: {
    width: 54,
    height: 54,
    borderRadius: 999,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  playerName: {
    maxWidth: '100%',
    fontSize: 13,
    lineHeight: 15,
    textAlign: 'center',
  },
  deviceIcon: {
    marginTop: 1,
  },
  hostBadge: {
    position: 'absolute',
    top: 6,
    right: 6,
    zIndex: 2,
    width: 19,
    height: 19,
    borderRadius: 999,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconAction: {
    position: 'absolute',
    top: 6,
    right: 6,
    zIndex: 2,
    width: 19,
    height: 19,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FF5A81',
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  iconActionLabel: {
    fontSize: 13,
    lineHeight: 13,
  },
  addCardButton: {
    minHeight: 128,
    borderRadius: 18,
    borderWidth: 1.8,
    borderColor: '#BFD3EC',
    backgroundColor: 'rgba(255,255,255,0.86)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#90BCEA',
    shadowOpacity: 0.18,
    shadowRadius: 9,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  addCardSymbol: {
    color: '#8E95A9',
    fontSize: 44,
    lineHeight: 44,
  },
  bottomDock: {
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderTopColor: 'rgba(0,0,0,0.08)',
    borderTopWidth: 1,
    shadowColor: '#9AAFD6',
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: -3 },
    elevation: 10,
  },
  startButton: {
    borderRadius: 999,
    minHeight: 58,
    shadowColor: '#FF6C6C',
    shadowOpacity: 0.34,
    shadowRadius: 13,
    shadowOffset: { width: 0, height: 7 },
    elevation: 8,
  },
});



