import { StyleSheet } from 'react-native';

export const secretRevealCardStyles = StyleSheet.create({
  cardShell: {
    minHeight: 468,
    borderRadius: 30,
    borderWidth: 1.2,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    shadowOpacity: 0.2,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10,
    paddingHorizontal: 18,
    paddingVertical: 18,
  },
  chargeGlowBorder: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 2,
    borderRadius: 30,
    shadowOffset: { width: 0, height: 0 },
    elevation: 9,
  },
  cardGloss: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 30,
  },
  flipCanvas: {
    width: '100%',
    minHeight: 408,
    paddingHorizontal: 20,
    paddingVertical: 22,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  flipFace: {
    ...StyleSheet.absoluteFillObject,
    backfaceVisibility: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 22,
    gap: 12,
  },
  avatarHalo: {
    width: 120,
    height: 120,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.2,
    marginBottom: 6,
  },
  holdProgressTrack: {
    width: 210,
    height: 8,
    borderRadius: 999,
    overflow: 'hidden',
    borderWidth: 1,
    marginTop: 4,
  },
  holdProgressFill: {
    height: '100%',
    borderRadius: 999,
  },
  hostBadge: {
    position: 'absolute',
    top: 16,
    right: 16,
    width: 32,
    height: 32,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  playerName: {
    fontSize: 34,
    lineHeight: 38,
    textAlign: 'center',
    maxWidth: '92%',
  },
  hintText: {
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
    opacity: 0.92,
  },
  subtleLabel: {
    fontSize: 11,
    lineHeight: 12,
    textTransform: 'uppercase',
    letterSpacing: 1.7,
  },
  numberWrap: {
    minWidth: 230,
    minHeight: 164,
    borderRadius: 24,
    borderWidth: 1.2,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  numberText: {
    fontSize: 110,
    lineHeight: 112,
  },
  revealedHeader: {
    alignItems: 'center',
    gap: 6,
  },
  revealedIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  waitingText: {
    fontSize: 15,
    lineHeight: 20,
    textAlign: 'center',
    maxWidth: '86%',
  },
});
