import { StyleSheet } from 'react-native';

export const secretPhaseStyles = StyleSheet.create({
  screenBackdrop: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'hidden',
  },
  phaseHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    paddingTop: 6,
  },
  phaseHeaderLeft: {
    flex: 1,
    gap: 2,
  },
  roundLabel: {
    fontSize: 11,
    lineHeight: 13,
    textTransform: 'uppercase',
    letterSpacing: 1.7,
  },
  gameTitle: {
    fontSize: 40,
    lineHeight: 42,
    letterSpacing: -0.8,
    textTransform: 'uppercase',
  },
  phaseHeaderRight: {
    alignItems: 'flex-end',
    gap: 7,
  },
  playerStack: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexWrap: 'wrap',
    columnGap: 6,
    rowGap: 6,
    maxWidth: 170,
  },
  playerBubble: {
    width: 28,
    height: 28,
    borderRadius: 999,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  plusBubbleLabel: {
    fontSize: 12,
    lineHeight: 12,
  },
  playersCountLabel: {
    fontSize: 10,
    lineHeight: 12,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  readyBadge: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 5,
  },
  readyBadgeText: {
    fontSize: 12,
    lineHeight: 14,
  },
  scaleCard: {
    borderWidth: 1,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 12,
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 5,
  },
  scaleGloss: {
    position: 'absolute',
    top: 0,
    right: 0,
    left: 0,
    height: '50%',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  scaleTitle: {
    fontSize: 11,
    lineHeight: 13,
    textAlign: 'center',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  scaleAxisRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  scaleEdgeLabel: {
    fontSize: 17,
    lineHeight: 20,
    flexShrink: 0,
    textTransform: 'uppercase',
  },
  scaleTrackWrap: {
    flex: 1,
    justifyContent: 'center',
  },
  scaleTrack: {
    flex: 1,
    height: 4,
    borderRadius: 999,
    position: 'relative',
    overflow: 'visible',
  },
  scaleTrackGradient: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 999,
  },
  scaleDotHalo: {
    position: 'absolute',
    width: 18,
    height: 18,
    borderRadius: 999,
    borderWidth: 1,
    top: -7,
    left: '50%',
    marginLeft: -9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scaleDot: {
    width: 6,
    height: 6,
    borderRadius: 999,
  },
  scaleThemeText: {
    fontSize: 24,
    lineHeight: 30,
    textAlign: 'center',
    letterSpacing: -0.2,
  },
});
