import { StyleSheet } from 'react-native';

const ORDERING_GRID_ROW_GAP = 4;
const ORDERING_GRID_COLUMN_GAP = 10;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  topBarSpacing: {
    paddingTop: 20,
    paddingBottom: 14,
  },
  errorStrip: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  errorText: {
    fontSize: 12,
    lineHeight: 16,
  },
  emptyWrap: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  themeWrap: {
    position: 'relative',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 146,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 12,
    borderWidth: 1.3,
    borderRadius: 24,
    shadowOpacity: 0.28,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 0 },
    elevation: 7,
  },
  themeText: {
    textAlign: 'center',
    fontSize: 34,
    lineHeight: 39,
    textShadowRadius: 18,
    letterSpacing: 0.5,
  },
  themeShineSweep: {
    position: 'absolute',
    left: -260,
    top: -30,
    bottom: -30,
    width: 90,
    borderRadius: 20,
  },
  voiceNotice: {
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  voiceNoticeText: {
    fontSize: 12,
    lineHeight: 17,
  },
  hostHintText: {
    fontSize: 12,
  },
  playersMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  playersSectionTitle: {
    fontSize: 17,
  },
  cardsViewport: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 8,
    paddingTop: 8,
    paddingBottom: 8,
  },
  emptyCardsState: {
    paddingHorizontal: 8,
    paddingVertical: 12,
  },
  emptyCardsText: {
    fontSize: 13,
    textAlign: 'center',
  },
  secretGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingBottom: 20,
  },
  secretCard: {
    width: '48.8%',
    minHeight: 92,
    borderWidth: 1.3,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 4,
    paddingHorizontal: 8,
    paddingTop: 7,
    paddingBottom: 3,
    overflow: 'hidden',
    position: 'relative',
    shadowOpacity: 0.36,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 0 },
    elevation: 4,
  },
  secretFrame: {
    position: 'absolute',
    top: 6,
    right: 6,
    bottom: 6,
    left: 6,
    borderRadius: 12,
    borderWidth: 1,
  },
  secretFrameInner: {
    position: 'absolute',
    top: 14,
    right: 14,
    bottom: 14,
    left: 14,
    borderRadius: 10,
    borderWidth: 1,
  },
  hostCrown: {
    position: 'absolute',
    top: 4,
    right: 6,
    zIndex: 2,
    transform: [{ scale: 1.2 }],
  },
  secretAvatar: {
    width: 46,
    height: 46,
    borderRadius: 999,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  secretLockWrap: {
    width: 34,
    height: 34,
    borderRadius: 999,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 6,
  },
  secretAvatarText: {
    fontSize: 16,
  },
  secretBurst: {
    position: 'absolute',
    top: 14,
    width: 54,
    height: 54,
    borderRadius: 999,
    zIndex: 1,
  },
  secretNumber: {
    marginTop: 4,
    fontSize: 30,
    lineHeight: 32,
    zIndex: 2,
  },
  secretName: {
    width: '100%',
    textAlign: 'center',
    fontSize: 12,
    lineHeight: 13,
  },
  secretHint: {
    marginTop: 2,
    fontSize: 11,
    lineHeight: 12,
    textAlign: 'center',
  },
  secretHeroOverlay: {
    borderWidth: 1.5,
    borderRadius: 26,
    minHeight: 360,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
    paddingHorizontal: 28,
    paddingVertical: 28,
    shadowOpacity: 0.66,
    shadowRadius: 26,
    shadowOffset: { width: 0, height: 0 },
    elevation: 14,
    overflow: 'hidden',
  },
  secretHeroFrame: {
    position: 'absolute',
    top: 12,
    right: 12,
    bottom: 12,
    left: 12,
    borderRadius: 20,
    borderWidth: 1,
  },
  secretHeroFrameInner: {
    position: 'absolute',
    top: 24,
    right: 24,
    bottom: 24,
    left: 24,
    borderRadius: 16,
    borderWidth: 1,
  },
  secretHeroName: {
    fontSize: 34,
    lineHeight: 36,
    textAlign: 'center',
  },
  secretHeroNumber: {
    fontSize: 98,
    lineHeight: 100,
  },
  secretHeroHint: {
    fontSize: 16,
    lineHeight: 20,
    textAlign: 'center',
  },
  remoteSignal: {
    marginTop: 2,
    width: 18,
    height: 18,
    borderRadius: 999,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  orderingGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: ORDERING_GRID_ROW_GAP,
    columnGap: ORDERING_GRID_COLUMN_GAP,
    paddingBottom: 4,
  },
  orderingCard: {
    width: '48.8%',
    padding: 0,
    minHeight: 88,
    position: 'relative',
  },
  orderingDragGlow: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 1.6,
    borderRadius: 12,
    shadowOpacity: 0.64,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 0 },
    elevation: 10,
    zIndex: 9,
  },
  flipShell: {
    minHeight: 62,
  },
  flipFace: {
    borderWidth: 1.4,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 6,
    backfaceVisibility: 'hidden',
  },
  flipBackFace: {
    ...StyleSheet.absoluteFillObject,
  },
  cornerBadgeWrap: {
    position: 'absolute',
    right: 8,
    top: 6,
    alignItems: 'center',
    zIndex: 6,
  },
  cardMainRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  avatarWrap: {
    width: 44,
    height: 44,
    borderWidth: 1,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    overflow: 'visible',
  },
  orderBadge: {
    position: 'relative',
    minWidth: 20,
    height: 20,
    borderRadius: 999,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
    zIndex: 4,
  },
  orderBadgeText: {
    fontSize: 12,
    lineHeight: 13,
  },
  avatarText: {
    fontSize: 18,
  },
  cardMeta: {
    flex: 1,
    gap: 4,
    paddingRight: 30,
  },
  playerName: {
    fontSize: 15,
  },
  playerHint: {
    fontSize: 11,
    lineHeight: 15,
  },
  revealedNumber: {
    fontSize: 22,
    lineHeight: 24,
  },
  rulesText: {
    fontSize: 14,
  },
});



