import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  emptyWrap: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  lobbyMilkOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.6)',
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 6,
    paddingBottom: 176,
    gap: 12,
    width: '100%',
    maxWidth: 620,
    alignSelf: 'center',
  },
  sessionPanel: {
    borderWidth: 0,
    borderRadius: 26,
    paddingHorizontal: 4,
    paddingVertical: 2,
    gap: 12,
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
  },
  sessionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  sessionTitle: {
    fontSize: 52,
    lineHeight: 54,
  },
  roomCodeWrap: {
    alignItems: 'stretch',
    gap: 6,
    marginTop: 8,
  },
  roomCodeActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    width: '100%',
  },
  roomCodeButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  roomCodeTilesWrap: {
    borderRadius: 0,
    borderWidth: 0,
    borderBottomWidth: 0,
    paddingHorizontal: 0,
    paddingVertical: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 5,
    flexShrink: 1,
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
  },
  roomCodeCharTile: {
    width: 34,
    height: 42,
    borderRadius: 14,
    borderWidth: 1.2,
    borderBottomWidth: 3,
    borderBottomColor: 'rgba(0,0,0,0.05)',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowOpacity: 0.28,
    shadowRadius: 7,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
  },
  roomCodeCharText: {
    fontSize: 20,
    lineHeight: 22,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  roomCodeCopyButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.3,
    shadowRadius: 6,
    shadowOffset: { width: 4, height: 4 },
    elevation: 7,
  },
  roomCodeMaskButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.3,
    shadowRadius: 6,
    shadowOffset: { width: 4, height: 4 },
    elevation: 7,
  },
  subtitle: {
    fontSize: 12,
    textAlign: 'center',
  },
  roomCodeFeedbackSlot: {
    minHeight: 14,
    marginTop: 2,
    marginBottom: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerBadges: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    gap: 7,
  },
  statusPill: {
    minHeight: 24,
    paddingHorizontal: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.04)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusPillText: {
    fontSize: 12,
    lineHeight: 13,
    letterSpacing: 0.3,
  },
  statusPillReady: {
    backgroundColor: '#EAE3FF',
  },
  statusPillMode: {
    backgroundColor: '#E1EEFF',
  },
  statusPillImpostor: {
    backgroundColor: '#FFE5F2',
  },
  statusPillOnline: {
    backgroundColor: '#E4FFF5',
  },
  statusPillNeutral: {
    backgroundColor: '#EFF1F9',
  },
  statusPillDanger: {
    backgroundColor: '#FFEAF0',
  },
  countdownPill: {
    alignSelf: 'center',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FFFFFF',
  },
  countdownLabel: {
    fontSize: 12,
  },
  countdownValue: {
    fontSize: 18,
    lineHeight: 18,
  },
  realtimeHint: {
    fontSize: 12,
    textAlign: 'center',
  },
  settingsIconButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.3,
    shadowRadius: 6,
    shadowOffset: { width: 4, height: 4 },
    elevation: 7,
  },
  settingsBlock: {
    gap: 8,
  },
  settingsLabel: {
    fontSize: 13,
  },
  settingsHint: {
    fontSize: 12,
  },
  settingsToggleRow: {
    flexDirection: 'row',
    gap: 8,
  },
  settingsToggle: {
    minHeight: 34,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  settingsToggleText: {
    fontSize: 13,
  },
  settingsStepperRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  stepperControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  stepperButton: {
    width: 30,
    height: 30,
    borderWidth: 1,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperButtonText: {
    fontSize: 19,
    lineHeight: 19,
  },
  stepperValue: {
    minWidth: 24,
    textAlign: 'center',
    fontSize: 15,
  },
  playersList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    alignContent: 'flex-start',
  },
  playersStage: {
    marginTop: 2,
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 10,
    backgroundColor: 'transparent',
  },
  emptyPlayersState: {
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  emptyPlayersText: {
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  playerCell: {
    minWidth: 0,
  },
  playerCard: {
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.6)',
    backgroundColor: '#FFFFFF',
    minHeight: 106,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
    overflow: 'visible',
  },
  playerCardPressable: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    paddingHorizontal: 8,
    minHeight: 100,
    backgroundColor: 'rgba(255,255,255,0.85)',
    borderRadius: 16,
  },
  shineGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 70,
    borderRadius: 16,
    pointerEvents: 'none',
  },
  avatarShell: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  playerAvatar: {
    width: 42,
    height: 42,
  },
  playerName: {
    maxWidth: '100%',
    fontSize: 10,
    lineHeight: 12,
    textAlign: 'center',
  },
  deviceIcon: {
    marginTop: 1,
  },
  hostBadge: {
    position: 'absolute',
    top: 2,
    right: 2,
    zIndex: 2,
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconAction: {
    position: 'absolute',
    top: 2,
    right: 2,
    zIndex: 2,
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderWidth: 0,
  },
  iconActionLabel: {
    fontSize: 20,
    lineHeight: 20,
  },
  bottomDock: {
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderTopColor: 'rgba(0,0,0,0.08)',
    borderTopWidth: 1,
    shadowColor: '#9AAFD6',
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: -3 },
    elevation: 10,
  },
  loadingWrap: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  loadingCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    backgroundColor: 'rgba(255,255,255,0.86)',
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 10,
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  loadingTitle: {
    fontSize: 24,
    lineHeight: 28,
    textAlign: 'center',
  },
  loadingSubtitle: {
    fontSize: 14,
    lineHeight: 19,
    textAlign: 'center',
  },
  loadingButton: {
    width: '100%',
    marginTop: 2,
  },
  leaveModal: {
    borderRadius: 22,
  },
  leaveMessage: {
    fontSize: 14,
    lineHeight: 20,
    marginTop: 2,
    marginBottom: 8,
  },
  leaveActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 8,
  },
  addPlayerModal: {
    borderRadius: 22,
  },
  addPlayerInput: {
    marginTop: 8,
  },
  addPlayerActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 10,
  },
});
