import { Locale } from '@/src/i18n';

export type SintoniaThemeCategory = {
  prompt: string;
  lowLabel: string;
  highLabel: string;
};

const sintoniaThemesPt: readonly SintoniaThemeCategory[] = [
  { prompt: 'Animais mais perigosos que se pode ter em casa', lowLabel: 'inofensivo', highLabel: 'perigoso' },
  { prompt: 'Objetos que mais doem ao pisar descalco', lowLabel: 'leve', highLabel: 'doloroso' },
  { prompt: 'Piores lugares para se estar durante um apocalipse', lowLabel: 'seguro', highLabel: 'caotico' },
  { prompt: 'Alimentos que mais causam briga por causa do sabor', lowLabel: 'pacifico', highLabel: 'polemico' },
  { prompt: 'Cores que mais chamam a atencao de longe', lowLabel: 'discreto', highLabel: 'chamativo' },
  { prompt: 'Itens indispensaveis em uma ilha deserta', lowLabel: 'opcional', highLabel: 'vital' },
  { prompt: 'Programas de TV mais dificeis de parar de assistir', lowLabel: 'curto', highLabel: 'viciante' },
  { prompt: 'Lugares mais desconfortaveis para passar a noite', lowLabel: 'aconchegante', highLabel: 'desconfortavel' },
  { prompt: 'Presentes de aniversario mais sem graca', lowLabel: 'incrivel', highLabel: 'semgraca' },
  { prompt: 'Profissoes mais estressantes do mundo', lowLabel: 'tranquilo', highLabel: 'estressante' },
  { prompt: 'Viloes de cinema mais malvados de todos', lowLabel: 'brando', highLabel: 'cruel' },
  { prompt: 'Cidades mais barulhentas para se viver', lowLabel: 'silenciosa', highLabel: 'barulhenta' },
  { prompt: 'Hobbies que mais exigem dinheiro', lowLabel: 'barato', highLabel: 'caro' },
  { prompt: 'Coisas que mais causam vergonha em publico', lowLabel: 'normal', highLabel: 'vergonhoso' },
  { prompt: 'Sons mais irritantes que o ser humano consegue ouvir', lowLabel: 'suave', highLabel: 'irritante' },
  { prompt: 'Frutas mais dificeis de descascar', lowLabel: 'facil', highLabel: 'dificil' },
  { prompt: 'Invencoes que mais mudaram a historia da humanidade', lowLabel: 'pontual', highLabel: 'revolucionaria' },
  { prompt: 'Eletrodomesticos que mais fazem falta quando quebram', lowLabel: 'dispensavel', highLabel: 'indispensavel' },
  { prompt: 'Pecas de roupa mais dificeis de combinar', lowLabel: 'versatil', highLabel: 'dificil' },
  { prompt: 'Esportes mais perigosos para praticar', lowLabel: 'seguro', highLabel: 'radical' },
  { prompt: 'Desenhos animados mais nostalgicos da infancia', lowLabel: 'esquecivel', highLabel: 'nostalgico' },
  { prompt: 'Cargos de trabalho com maior responsabilidade', lowLabel: 'leve', highLabel: 'pesado' },
  { prompt: 'Mentiras que as pessoas mais contam no dia a dia', lowLabel: 'rara', highLabel: 'comum' },
  { prompt: 'Lugares onde o tempo parece passar mais devagar', lowLabel: 'rapido', highLabel: 'lento' },
  { prompt: 'Objetos que mais somem dentro de casa', lowLabel: 'fixo', highLabel: 'sumico' },
  { prompt: 'Bebidas que mais causam ressaca no dia seguinte', lowLabel: 'leve', highLabel: 'pesada' },
  { prompt: 'Animais que seriam os piores animais de estimacao', lowLabel: 'fofo', highLabel: 'terrivel' },
  { prompt: 'Coisas que mais dao medo no escuro', lowLabel: 'tranquilo', highLabel: 'assustador' },
  { prompt: 'Tarefas domesticas que mais dao preguica de fazer', lowLabel: 'deboa', highLabel: 'cansativa' },
  { prompt: 'Superpoderes mais uteis para a vida real', lowLabel: 'limitado', highLabel: 'util' },
  { prompt: 'Piores lugares para o celular tocar alto', lowLabel: 'deboa', highLabel: 'constrangedor' },
  { prompt: 'Pessoas que mais demoram para se arrumar', lowLabel: 'agil', highLabel: 'demorado' },
  { prompt: 'Meios de transporte mais desconfortaveis', lowLabel: 'confortavel', highLabel: 'apertado' },
  { prompt: 'Momentos da vida em que sentimos mais sono', lowLabel: 'acordado', highLabel: 'sonolento' },
  { prompt: 'Comidas de festa que acabam mais rapido', lowLabel: 'sobrando', highLabel: 'disputado' },
  { prompt: 'Tecnologias que mais rapidamente ficam ultrapassadas', lowLabel: 'duravel', highLabel: 'descartavel' },
  { prompt: 'Estilos musicais mais dificeis de dancar', lowLabel: 'facil', highLabel: 'complicado' },
  { prompt: 'Coisas que mais estragam o humor de alguem', lowLabel: 'neutro', highLabel: 'estressante' },
  { prompt: 'Animais que seriam os melhores detetives', lowLabel: 'desatento', highLabel: 'perspicaz' },
  { prompt: 'Paises mais dificeis de se aprender a lingua', lowLabel: 'simples', highLabel: 'complexa' },
  { prompt: 'Cenas de filmes que mais fazem as pessoas chorarem', lowLabel: 'fria', highLabel: 'emocionante' },
  { prompt: 'Objetos que mais acumulamos sem precisar', lowLabel: 'util', highLabel: 'acumulado' },
  { prompt: 'Rituais matinais que mais levam tempo', lowLabel: 'rapido', highLabel: 'demorado' },
  { prompt: 'Piores lugares para se ter uma primeira conversa', lowLabel: 'confortavel', highLabel: 'constrangedor' },
  { prompt: 'Coisas que mais causam arrependimento apos comprar', lowLabel: 'acerto', highLabel: 'arrependimento' },
  { prompt: 'Jogos de tabuleiro que mais causam brigas', lowLabel: 'leve', highLabel: 'caotico' },
  { prompt: 'Cheiros que mais trazem memorias da infancia', lowLabel: 'fraco', highLabel: 'nostalgico' },
  { prompt: 'Habilidades que mais impressionam em uma festa', lowLabel: 'basica', highLabel: 'impressionante' },
  { prompt: 'Climas que mais dao vontade de ficar na cama', lowLabel: 'ativo', highLabel: 'preguicoso' },
  { prompt: 'Atividades que mais fazem o tempo voar', lowLabel: 'lento', highLabel: 'absorvente' },
] as const;

const sintoniaThemesEn: readonly SintoniaThemeCategory[] = [
  { prompt: 'Most dangerous animals to keep at home', lowLabel: 'harmless', highLabel: 'dangerous' },
  { prompt: 'Objects that hurt the most to step on barefoot', lowLabel: 'light', highLabel: 'painful' },
  { prompt: 'Worst places to be during an apocalypse', lowLabel: 'safe', highLabel: 'chaotic' },
  { prompt: 'Foods that cause the biggest fights over taste', lowLabel: 'peaceful', highLabel: 'polarizing' },
  { prompt: 'Colors that stand out the most from far away', lowLabel: 'subtle', highLabel: 'flashy' },
  { prompt: 'Must-have items on a desert island', lowLabel: 'optional', highLabel: 'essential' },
  { prompt: 'TV shows that are hardest to stop watching', lowLabel: 'quick', highLabel: 'addictive' },
  { prompt: 'Most uncomfortable places to spend the night', lowLabel: 'cozy', highLabel: 'uncomfortable' },
  { prompt: 'Most boring birthday gifts', lowLabel: 'amazing', highLabel: 'boring' },
  { prompt: 'Most stressful jobs in the world', lowLabel: 'calm', highLabel: 'stressful' },
  { prompt: 'Most evil movie villains of all time', lowLabel: 'mild', highLabel: 'cruel' },
  { prompt: 'Noisiest cities to live in', lowLabel: 'quiet', highLabel: 'noisy' },
  { prompt: 'Hobbies that demand the most money', lowLabel: 'cheap', highLabel: 'expensive' },
  { prompt: 'Things that cause the most public embarrassment', lowLabel: 'normal', highLabel: 'awkward' },
  { prompt: 'Most irritating sounds humans can hear', lowLabel: 'soft', highLabel: 'irritating' },
  { prompt: 'Hardest fruits to peel', lowLabel: 'easy', highLabel: 'hard' },
  { prompt: 'Inventions that changed human history the most', lowLabel: 'minor', highLabel: 'revolutionary' },
  { prompt: 'Home appliances most missed when they break', lowLabel: 'dispensable', highLabel: 'critical' },
  { prompt: 'Clothing pieces that are hardest to match', lowLabel: 'versatile', highLabel: 'tricky' },
  { prompt: 'Most dangerous sports to practice', lowLabel: 'safe', highLabel: 'extreme' },
  { prompt: 'Most nostalgic childhood cartoons', lowLabel: 'forgettable', highLabel: 'nostalgic' },
  { prompt: 'Job roles with the greatest responsibility', lowLabel: 'light', highLabel: 'heavy' },
  { prompt: 'Lies people tell most in daily life', lowLabel: 'rare', highLabel: 'common' },
  { prompt: 'Places where time seems to move slower', lowLabel: 'fast', highLabel: 'slow' },
  { prompt: 'Objects that disappear the most inside the house', lowLabel: 'fixed', highLabel: 'missing' },
  { prompt: 'Drinks that cause the worst hangover next day', lowLabel: 'mild', highLabel: 'brutal' },
  { prompt: 'Animals that would make the worst pets', lowLabel: 'cute', highLabel: 'terrible' },
  { prompt: 'Things that scare people the most in the dark', lowLabel: 'calm', highLabel: 'scary' },
  { prompt: 'Household chores people are laziest to do', lowLabel: 'easy', highLabel: 'exhausting' },
  { prompt: 'Most useful superpowers for real life', lowLabel: 'limited', highLabel: 'useful' },
  { prompt: 'Worst places for a loud phone ringtone', lowLabel: 'fine', highLabel: 'awkward' },
  { prompt: 'People who take the longest to get ready', lowLabel: 'quick', highLabel: 'slow' },
  { prompt: 'Most uncomfortable transportation types', lowLabel: 'comfortable', highLabel: 'cramped' },
  { prompt: 'Life moments when we feel the sleepiest', lowLabel: 'awake', highLabel: 'sleepy' },
  { prompt: 'Party foods that run out the fastest', lowLabel: 'leftover', highLabel: 'disputed' },
  { prompt: 'Technologies that become outdated the fastest', lowLabel: 'durable', highLabel: 'disposable' },
  { prompt: 'Music styles that are hardest to dance to', lowLabel: 'easy', highLabel: 'complex' },
  { prompt: 'Things that ruin someone mood the fastest', lowLabel: 'neutral', highLabel: 'stressful' },
  { prompt: 'Animals that would be the best detectives', lowLabel: 'clueless', highLabel: 'sharp' },
  { prompt: 'Countries with the hardest language to learn', lowLabel: 'simple', highLabel: 'complex' },
  { prompt: 'Movie scenes that make people cry the most', lowLabel: 'cold', highLabel: 'emotional' },
  { prompt: 'Objects we keep accumulating without needing', lowLabel: 'useful', highLabel: 'cluttered' },
  { prompt: 'Morning rituals that take the most time', lowLabel: 'fast', highLabel: 'slow' },
  { prompt: 'Worst places to have a first conversation', lowLabel: 'comfortable', highLabel: 'awkward' },
  { prompt: 'Things that cause the most regret after buying', lowLabel: 'smart', highLabel: 'regret' },
  { prompt: 'Board games that cause the most arguments', lowLabel: 'light', highLabel: 'chaotic' },
  { prompt: 'Smells that bring back childhood memories', lowLabel: 'faint', highLabel: 'nostalgic' },
  { prompt: 'Skills that impress the most at a party', lowLabel: 'basic', highLabel: 'impressive' },
  { prompt: 'Weather conditions that make us stay in bed', lowLabel: 'active', highLabel: 'lazy' },
  { prompt: 'Activities that make time fly the most', lowLabel: 'slow', highLabel: 'absorbing' },
] as const;

export const getSintoniaThemes = (locale: Locale): readonly SintoniaThemeCategory[] =>
  locale === 'en' ? sintoniaThemesEn : sintoniaThemesPt;

export const sintoniaThemeCount = sintoniaThemesPt.length;
