import { Locale } from '@/src/i18n';

const sintoniaThemesPt = [
  'Animais mais perigosos que se pode ter em casa',
  'Objetos que mais doem ao pisar descalço',
  'Piores lugares para se estar durante um apocalipse',
  'Alimentos que mais causam briga por causa do sabor',
  'Cores que mais chamam a atenção de longe',
  'Itens indispensáveis em uma ilha deserta',
  'Programas de TV mais difíceis de parar de assistir',
  'Lugares mais desconfortáveis para passar a noite',
  'Presentes de aniversário mais sem graça',
  'Profissões mais estressantes do mundo',
  'Vilões de cinema mais malvados de todos',
  'Cidades mais barulhentas para se viver',
  'Hobbies que mais exigem dinheiro',
  'Coisas que mais causam vergonha em público',
  'Sons mais irritantes que o ser humano consegue ouvir',
  'Frutas mais difíceis de descascar',
  'Invenções que mais mudaram a história da humanidade',
  'Eletrodomésticos que mais fazem falta quando quebram',
  'Peças de roupa mais difíceis de combinar',
  'Esportes mais perigosos para praticar',
  'Desenhos animados mais nostálgicos da infância',
  'Cargos de trabalho com maior responsabilidade',
  'Mentiras que as pessoas mais contam no dia a dia',
  'Lugares onde o tempo parece passar mais devagar',
  'Objetos que mais somem dentro de casa',
  'Bebidas que mais causam ressaca no dia seguinte',
  'Animais que seriam os piores animais de estimação',
  'Coisas que mais dão medo no escuro',
  'Tarefas domésticas que mais dão preguiça de fazer',
  'Superpoderes mais úteis para a vida real',
  'Piores lugares para o celular tocar alto',
  'Pessoas que mais demoram para se arrumar',
  'Meios de transporte mais desconfortáveis',
  'Momentos da vida em que sentimos mais sono',
  'Comidas de festa que acabam mais rápido',
  'Tecnologias que mais rapidamente ficam ultrapassadas',
  'Estilos musicais mais difíceis de dançar',
  'Coisas que mais estragam o humor de alguém',
  'Animais que seriam os melhores detetives',
  'Países mais difíceis de se aprender a língua',
  'Cenas de filmes que mais fazem as pessoas chorarem',
  'Objetos que mais acumulamos sem precisar',
  'Rituais matinais que mais levam tempo',
  'Piores lugares para se ter uma primeira conversa',
  'Coisas que mais causam arrependimento após comprar',
  'Jogos de tabuleiro que mais causam brigas',
  'Cheiros que mais trazem memórias da infância',
  'Habilidades que mais impressionam em uma festa',
  'Climas que mais dão vontade de ficar na cama',
  'Atividades que mais fazem o tempo voar',
] as const;

const sintoniaThemesEn = [
  'Most dangerous animals to keep at home',
  'Objects that hurt the most to step on barefoot',
  'Worst places to be during an apocalypse',
  'Foods that cause the biggest fights over taste',
  'Colors that stand out the most from far away',
  'Must-have items on a desert island',
  'TV shows that are hardest to stop watching',
  'Most uncomfortable places to spend the night',
  'Most boring birthday gifts',
  'Most stressful jobs in the world',
  'Most evil movie villains of all time',
  'Noisiest cities to live in',
  'Hobbies that demand the most money',
  'Things that cause the most public embarrassment',
  'Most irritating sounds humans can hear',
  'Hardest fruits to peel',
  'Inventions that changed human history the most',
  'Home appliances most missed when they break',
  'Clothing pieces that are hardest to match',
  'Most dangerous sports to practice',
  'Most nostalgic childhood cartoons',
  'Job roles with the greatest responsibility',
  'Lies people tell most in daily life',
  'Places where time seems to move slower',
  'Objects that disappear the most inside the house',
  'Drinks that cause the worst hangover next day',
  'Animals that would make the worst pets',
  'Things that scare people the most in the dark',
  'Household chores people are laziest to do',
  'Most useful superpowers for real life',
  'Worst places for a loud phone ringtone',
  'People who take the longest to get ready',
  'Most uncomfortable transportation types',
  'Life moments when we feel the sleepiest',
  'Party foods that run out the fastest',
  'Technologies that become outdated the fastest',
  'Music styles that are hardest to dance to',
  'Things that ruin someone mood the fastest',
  'Animals that would be the best detectives',
  'Countries with the hardest language to learn',
  'Movie scenes that make people cry the most',
  'Objects we keep accumulating without needing',
  'Morning rituals that take the most time',
  'Worst places to have a first conversation',
  'Things that cause the most regret after buying',
  'Board games that cause the most arguments',
  'Smells that bring back childhood memories',
  'Skills that impress the most at a party',
  'Weather conditions that make us stay in bed',
  'Activities that make time fly the most',
] as const;

export const getSintoniaThemes = (locale: Locale): readonly string[] =>
  locale === 'en' ? sintoniaThemesEn : sintoniaThemesPt;

export const sintoniaThemeCount = sintoniaThemesPt.length;
