import { StyleSheet } from 'react-native';

export const cluesPhaseStyles = StyleSheet.create({
  section: {
    gap: 18,
  },
  heroPanel: {
    borderWidth: 1,
    borderRadius: 30,
    paddingHorizontal: 20,
    paddingVertical: 20,
    gap: 16,
    shadowOpacity: 0.1,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  heroHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  heroCopy: {
    flex: 1,
    gap: 4,
  },
  heroEyebrow: {
    fontSize: 11,
    lineHeight: 13,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  heroTitle: {
    fontSize: 34,
    lineHeight: 36,
  },
  heroHint: {
    fontSize: 13,
    lineHeight: 17,
  },
  progressBadge: {
    minHeight: 34,
    minWidth: 70,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressBadgeText: {
    fontSize: 12,
    lineHeight: 13,
    letterSpacing: 0.1,
    textAlign: 'center',
  },
  progressStepsRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: 10,
  },
  progressStepItem: {
    width: 58,
    alignItems: 'center',
    gap: 6,
  },
  progressStepAvatarFocus: {
    width: 58,
    height: 58,
    borderRadius: 999,
    borderWidth: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressStepAvatarSide: {
    width: 40,
    height: 40,
    borderRadius: 999,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressStepTextFocus: {
    fontSize: 12,
    lineHeight: 14,
    textAlign: 'center',
  },
  progressStepTextSide: {
    fontSize: 11,
    lineHeight: 13,
    textAlign: 'center',
  },
  heroBody: {
    paddingTop: 2,
  },
  rosterSection: {
    gap: 8,
  },
  rosterHeader: {
    gap: 4,
    paddingHorizontal: 2,
  },
  rosterEyebrow: {
    fontSize: 11,
    lineHeight: 12,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  rosterTitle: {
    fontSize: 15,
    lineHeight: 18,
  },
  progressTrack: {
    width: '100%',
    height: 14,
    borderRadius: 999,
    borderWidth: 1,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
  },
  cardCell: {
    minWidth: 0,
  },
  playerCard: {
    borderWidth: 1,
    borderRadius: 24,
    paddingHorizontal: 15,
    paddingVertical: 14,
    gap: 9,
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  playerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  avatarWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  playerMeta: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  playerMetaLabel: {
    fontSize: 10,
    lineHeight: 12,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  playerName: {
    fontSize: 18,
    lineHeight: 20,
  },
  historyCountBadge: {
    minWidth: 28,
    height: 28,
    borderRadius: 999,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  historyCountText: {
    fontSize: 11,
    lineHeight: 12,
  },
  playerStatusInline: {
    fontSize: 12,
    lineHeight: 14,
  },
  emphasisLabel: {
    fontSize: 16,
    lineHeight: 19,
    minHeight: 24,
  },
  historyBlock: {
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 5,
  },
  historyLabel: {
    fontSize: 10,
    lineHeight: 12,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  historyList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  historyChip: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  historyChipText: {
    fontSize: 11,
    lineHeight: 13,
  },
  actionButton: {
    width: '100%',
  },
  composerStage: {
    paddingTop: 4,
  },
  composerCard: {
    borderWidth: 1,
    borderRadius: 24,
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 12,
  },
  composerHelper: {
    fontSize: 14,
    lineHeight: 18,
  },
  composerInput: {
    marginTop: 0,
  },
  passiveDockPill: {
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  passiveDockPillText: {
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'left',
  },
});
