import { StyleSheet } from 'react-native';

export const impostorPhaseStyles = StyleSheet.create({
  activeVoterCard: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 6,
  },
  activeVoterLabel: {
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    fontWeight: '700',
    textAlign: 'center',
  },
  activeVoterName: {
    fontSize: 22,
    lineHeight: 26,
    fontWeight: '800',
    textAlign: 'center',
  },
  decisionButton: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 18,
    minHeight: 64,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 4,
  },
  decisionButtonHint: {
    fontSize: 12,
    lineHeight: 15,
    textAlign: 'center',
  },
  decisionButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  decisionRow: {
    borderWidth: 1,
    borderRadius: 24,
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 12,
  },
  decisionStage: { gap: 14 },
  guessCard: {
    borderWidth: 1.2,
    borderRadius: 24,
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 10,
  },
  guessCardHint: {
    fontSize: 13,
    lineHeight: 18,
  },
  guessCardTitle: {
    fontSize: 18,
    lineHeight: 22,
  },
  guessStage: { gap: 14 },
  guessStageHero: {
    borderWidth: 1.2,
    borderRadius: 28,
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 8,
  },
  guessStageHint: {
    fontSize: 14,
    lineHeight: 20,
  },
  guessStageLabel: {
    fontSize: 11,
    lineHeight: 13,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  guessStageTitle: {
    fontSize: 28,
    lineHeight: 31,
  },
  input: {},
  playerCard: {
    borderWidth: 1.2,
    borderRadius: 18,
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  resultActions: { gap: 8 },
  resultBlock: {
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 10,
  },
  resultBlockTitle: {
    fontSize: 16,
    fontWeight: '700',
  },
  resultBlockLabel: {
    fontSize: 12,
  },
  resultCard: {
    gap: 14,
  },
  resultImpostorCard: {
    alignItems: 'center',
    gap: 4,
  },
  resultImpostorName: {
    fontSize: 13,
    fontWeight: '700',
  },
  resultImpostorRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  resultPromptRow: {
    gap: 4,
  },
  resultPromptValue: {
    fontSize: 19,
    lineHeight: 23,
    fontWeight: '700',
  },
  resultStateBanner: {
    borderWidth: 1.4,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  resultStateSubtitle: {
    fontSize: 16,
    fontWeight: '700',
  },
  resultStateTitle: {
    fontSize: 22,
    textTransform: 'uppercase',
    letterSpacing: 1.1,
    fontWeight: '800',
    textAlign: 'center',
  },
  skipButton: {
    alignSelf: 'flex-start',
    minHeight: 30,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  voteBoardWrap: {
    position: 'relative',
    borderRadius: 22,
    borderWidth: 1.2,
    overflow: 'visible',
    padding: 8,
    gap: 10,
  },
  voteMapRow: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 9,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  voteMapTarget: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minWidth: 100,
  },
  voteMapVoters: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 4,
  },
  votePlayerCard: {
    width: '100%',
    minHeight: 74,
    paddingHorizontal: 11,
    paddingVertical: 11,
    alignItems: 'flex-start',
    justifyContent: 'center',
    gap: 0,
  },
  votePlayerCell: {
    width: '47%',
    minWidth: 0,
    marginBottom: 10,
  },
  votePlayerName: {
    flex: 1,
    textAlign: 'left',
    fontSize: 14,
    lineHeight: 18,
  },
  votePlayerRole: {
    fontSize: 11,
    lineHeight: 13,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  votePlayerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    width: '100%',
  },
  votePrivacyOverlay: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 1,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    gap: 10,
  },
  votePrivacyText: {
    fontSize: 12,
    lineHeight: 17,
    textAlign: 'center',
  },
  voteProgressDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
    borderWidth: 1,
  },
  voteProgressDots: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  voteSelectedCard: {
    shadowOpacity: 0.72,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 0 },
    elevation: 14,
  },
  voteStage: { gap: 14 },
  voteGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  voteSummary: {
    borderWidth: 1.2,
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 6,
  },
});
