import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  emptyWrap: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  root: {
    gap: 12,
  },
  phaseGuide: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  phaseGuideText: {
    fontSize: 12,
    lineHeight: 17,
  },
  errorStrip: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  errorText: {
    fontSize: 12,
    lineHeight: 16,
  },
  content: {
    gap: 12,
    paddingBottom: 24,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  playerCard: {
    width: '31%',
    borderWidth: 1.2,
    borderRadius: 14,
    paddingHorizontal: 8,
    paddingVertical: 10,
    alignItems: 'center',
    gap: 8,
  },
  revealPlayerCard: {
    position: 'relative',
    overflow: 'hidden',
    minHeight: 132,
    justifyContent: 'center',
  },
  revealCardFrame: {
    position: 'absolute',
    top: 7,
    right: 7,
    bottom: 7,
    left: 7,
    borderWidth: 1,
    borderRadius: 12,
  },
  revealLock: {
    width: 30,
    height: 30,
    borderRadius: 999,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  revealHint: {
    fontSize: 11,
    lineHeight: 12,
    textAlign: 'center',
  },
  revealHeroCard: {
    borderWidth: 1.5,
    borderRadius: 26,
    minHeight: 360,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
    paddingHorizontal: 28,
    paddingVertical: 28,
    shadowOpacity: 0.68,
    shadowRadius: 26,
    shadowOffset: { width: 0, height: 0 },
    elevation: 15,
    overflow: 'hidden',
  },
  revealHeroFrame: {
    position: 'absolute',
    top: 12,
    right: 12,
    bottom: 12,
    left: 12,
    borderRadius: 20,
    borderWidth: 1,
  },
  revealHeroFrameInner: {
    position: 'absolute',
    top: 24,
    right: 24,
    bottom: 24,
    left: 24,
    borderRadius: 16,
    borderWidth: 1,
  },
  revealHeroName: {
    fontSize: 34,
    lineHeight: 36,
    textAlign: 'center',
  },
  revealHeroSecret: {
    fontSize: 44,
    lineHeight: 50,
    fontWeight: '800',
    textAlign: 'center',
  },
  revealHeroHint: {
    fontSize: 15,
    lineHeight: 18,
    textAlign: 'center',
  },
  playerName: {
    fontSize: 13,
  },
  decisionRow: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 8,
  },
  decisionButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  decisionButton: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 10,
    minHeight: 34,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  input: {},
  promptBox: {
    borderWidth: 1.2,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 8,
    overflow: 'hidden',
    position: 'relative',
  },
  promptFogLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  promptHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  progressWrap: {
    gap: 8,
  },
  progressTrack: {
    width: '100%',
    height: 8,
    borderRadius: 999,
    borderWidth: 1,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
  },
  cluesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  clueSlot: {
    width: '48.5%',
    borderWidth: 1.2,
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginBottom: 10,
    gap: 7,
  },
  clueSlotHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  clueSlotContentRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    minHeight: 68,
  },
  clueSlotDivider: {
    width: 1,
    marginHorizontal: 8,
    alignSelf: 'stretch',
  },
  clueSlotMainClueCol: {
    flex: 1,
    justifyContent: 'flex-start',
  },
  clueHistoryCol: {
    width: '42%',
    justifyContent: 'flex-start',
  },
  clueSlotValue: {
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '700',
    letterSpacing: 0.4,
    minHeight: 22,
  },
  clueSlotName: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '600',
  },
  clueHistoryText: {
    fontSize: 11,
    lineHeight: 14,
  },
  clueHistoryList: {
    gap: 2,
  },
  voteSelectedCard: {
    shadowOpacity: 0.72,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 0 },
    elevation: 14,
  },
  voteGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  votePlayerCell: {
    width: '47%',
    minWidth: 0,
    marginBottom: 8,
  },
  votePlayerCard: {
    width: '100%',
    minHeight: 66,
    paddingHorizontal: 9,
    paddingVertical: 9,
    alignItems: 'flex-start',
    justifyContent: 'center',
    gap: 0,
  },
  votePlayerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    width: '100%',
  },
  votePlayerName: {
    flex: 1,
    textAlign: 'left',
    fontSize: 14,
    lineHeight: 18,
  },
  activeVoterCard: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 6,
  },
  activeVoterLabel: {
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    fontWeight: '700',
    textAlign: 'center',
  },
  activeVoterName: {
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '800',
    textAlign: 'center',
  },
  voteProgressDots: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  voteProgressDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
    borderWidth: 1,
  },
  voteBoardWrap: {
    position: 'relative',
    borderRadius: 12,
    borderWidth: 1,
    overflow: 'visible',
    padding: 6,
  },
  votePrivacyOverlay: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 1,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    gap: 10,
  },
  votePrivacyText: {
    fontSize: 12,
    lineHeight: 17,
    textAlign: 'center',
  },
  voteSummary: {
    borderWidth: 1.2,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 4,
  },
  resultCard: {
    gap: 12,
  },
  skipButton: {
    alignSelf: 'flex-start',
    minHeight: 30,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultStateBanner: {
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  resultStateTitle: {
    fontSize: 20,
    textTransform: 'uppercase',
    letterSpacing: 1.1,
    fontWeight: '800',
  },
  resultStateSubtitle: {
    fontSize: 16,
    fontWeight: '700',
  },
  resultBlock: {
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
  },
  resultBlockTitle: {
    fontSize: 15,
    fontWeight: '700',
  },
  resultBlockLabel: {
    fontSize: 12,
  },
  resultPromptRow: {
    gap: 2,
  },
  resultPromptValue: {
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '700',
  },
  resultImpostorRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  resultImpostorCard: {
    alignItems: 'center',
    gap: 4,
  },
  resultImpostorName: {
    fontSize: 13,
    fontWeight: '700',
  },
  voteMapRow: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  voteMapTarget: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minWidth: 100,
  },
  voteMapVoters: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 4,
  },
  resultActions: {
    gap: 8,
  },
});


