import { StyleSheet } from 'react-native';

export const revealCardStyles = StyleSheet.create({
  avatarHalo: {
    width: 112,
    height: 112,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.6,
    marginBottom: 8,
  },
  cardGloss: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 28,
  },
  cardBackGlow: {
    position: 'absolute',
    left: '17%',
    right: '17%',
    bottom: 8,
    height: 126,
    borderRadius: 999,
    shadowOffset: { width: 0, height: 22 },
    elevation: 10,
  },
  cardShell: {
    width: '84%',
    maxWidth: 320,
    minHeight: 392,
    alignSelf: 'center',
    borderRadius: 28,
    borderWidth: 2.6,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    shadowOpacity: 0.22,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 14,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  cardInset: {
    position: 'absolute',
    top: 6,
    right: 6,
    bottom: 6,
    left: 6,
    borderRadius: 24,
  },
  cardFrameOuter: {
    position: 'absolute',
    top: 10,
    right: 10,
    bottom: 10,
    left: 10,
    borderRadius: 23,
    borderWidth: 1.8,
  },
  cardFrameInner: {
    position: 'absolute',
    top: 18,
    right: 18,
    bottom: 18,
    left: 18,
    borderRadius: 18,
    borderWidth: 1.2,
  },
  cardToneBackground: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 28,
  },
  chargeGlowBorder: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 2.8,
    borderRadius: 28,
    shadowOffset: { width: 0, height: 0 },
    elevation: 11,
  },
  chargeFrameInnerGlow: {
    position: 'absolute',
    top: 18,
    right: 18,
    bottom: 18,
    left: 18,
    borderRadius: 18,
    borderWidth: 1.8,
    shadowOffset: { width: 0, height: 0 },
    elevation: 8,
  },
  flipCanvas: {
    width: '100%',
    minHeight: 320,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 18,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  flipFace: {
    ...StyleSheet.absoluteFillObject,
    backfaceVisibility: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 18,
    gap: 10,
  },
  hintText: {
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
    opacity: 0.92,
  },
  frontHintText: {
    fontSize: 14,
    lineHeight: 18,
    textAlign: 'center',
    maxWidth: '88%',
  },
  hostBadge: {
    position: 'absolute',
    top: 18,
    right: 18,
    width: 34,
    height: 34,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.4,
  },
  impostorSurface: {
    minHeight: 198,
    paddingHorizontal: 26,
    gap: 12,
  },
  impostorWordmark: {
    fontSize: 34,
    lineHeight: 36,
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 2.2,
  },
  impostorHintValue: {
    fontSize: 20,
    lineHeight: 24,
    textAlign: 'center',
    maxWidth: '94%',
  },
  impostorText: {
    fontSize: 36,
    lineHeight: 42,
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    maxWidth: '94%',
  },
  numberText: {
    fontSize: 110,
    lineHeight: 112,
    textAlign: 'center',
    maxWidth: '100%',
  },
  paperAccentLine: {
    position: 'absolute',
    top: 18,
    right: 22,
    width: 40,
    height: 4,
    borderRadius: 999,
  },
  paperGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  paperTextureLineBottom: {
    position: 'absolute',
    right: 28,
    bottom: 22,
    left: 28,
    height: 1,
    borderRadius: 999,
  },
  paperTextureLineTop: {
    position: 'absolute',
    top: 20,
    right: 20,
    left: 20,
    height: 1,
    borderRadius: 999,
  },
  paperToneFrame: {
    position: 'absolute',
    top: 12,
    right: 12,
    bottom: 12,
    left: 12,
    borderRadius: 20,
    borderWidth: 1,
  },
  paperToneFrameInner: {
    position: 'absolute',
    top: 22,
    right: 22,
    bottom: 22,
    left: 22,
    borderRadius: 16,
    borderWidth: 1,
  },
  playerName: {
    fontSize: 30,
    lineHeight: 34,
    textAlign: 'center',
    maxWidth: '92%',
  },
  holdProgressTrack: {
    width: 180,
    height: 10,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  holdProgressFill: {
    height: 6,
    borderRadius: 999,
    marginLeft: 2,
  },
  revealSurface: {
    minWidth: 230,
    minHeight: 164,
    borderRadius: 24,
    borderWidth: 1.2,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 14,
    overflow: 'hidden',
    position: 'relative',
  },
  revealedHeader: {
    alignItems: 'center',
    gap: 6,
  },
  revealedIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  secretSurface: {
    minHeight: 188,
    paddingHorizontal: 24,
  },
  secretText: {
    fontSize: 36,
    lineHeight: 42,
    textAlign: 'center',
    maxWidth: '94%',
  },
  subtleLabel: {
    fontSize: 11,
    lineHeight: 12,
    textTransform: 'uppercase',
    letterSpacing: 1.7,
  },
  waitingText: {
    fontSize: 15,
    lineHeight: 20,
    textAlign: 'center',
    maxWidth: '86%',
  },
});
